[package]
name = "lc3-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
console = "0.15"
raw_tty = "0.1"
termios = "0.3"
timeout-readwrite = "0.4"
