name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make build
    - name: Run tests
      run: make test 
    - name: Run clippy
      run: make clippy
    - name: Run format
      run: make format-check
